'use strict';
const {test}=require('node:test'),a=require('node:assert/strict');
const V=require('../src/vfs'),C=require('../src/game-core'),P=require('../src/game-presentation'),IO=require('../src/game-import'),ZIP=require('../src/zip');
function save(info={姓名:'林青'}){const t=V.createTree();V.writeFile(t,'/workspace/Player-p/基础信息.json',JSON.stringify(info));V.writeFile(t,'/workspace/Player-p/背包.json','[]');V.writeFile(t,'/workspace/世界状态和世界规则/世界共识.json','{"世界时间":"清晨"}');return C.createSave('测试',t);}
const plan={Countdowns:'无',Pending_Triggers:[],Forced_Checks:'无'};
test('known index paths display readable names while ordinary slash text stays intact',()=>{const s=save({穿戴:{手部:'存档-索引-物品/key'},描述:'HP/MP',备注:'https://example.test/a'});V.writeFile(s.tree,'/workspace/存档-索引-物品/key/物品基础信息.json','{"名称":"铜钥匙"}');a.equal(C.player(s).info.穿戴.手部,'铜钥匙');a.equal(C.player(s).info.描述,'HP/MP');a.equal(C.player(s).info.备注,'https://example.test/a');});
function finish(s){C.execute(s,'trigger_next_round',{phase_plan:plan},'trigger');a.equal(C.execute(s,'append_story',{content:'发现铜钥匙',one_line_summary_of_content:'取得钥匙'},'story').ok,true);return C.execute(s,'end_the_round',{NEXT_TURN_CACHE:{Story_Phase:'游戏循环',Game_World_Time:'午后'}},'end');}
test('completed rounds become searchable files and rollback removes the archive',()=>{const s=save();C.beginRound(s,'搜寻钥匙');a.equal(finish(s).ok,true);const dir=V.resolve(s.tree,['workspace','过往回合历史记忆','Round_1_Time_午后']);a.ok(dir);a.deepEqual(Object.keys(dir.children).sort(),['ROUND_CACHE.xml','回合总结.txt','回合情节.json','玩家输入.json'].sort());a.match(dir.children['回合情节.json'].content,/铜钥匙/);a.equal(s.summaries[0].worldTime,'午后');a.ok(s.summaries[0].at);a.equal(s.snapshots[0].worldTime,'清晨');a.ok(s.snapshots[0].at);const before=JSON.stringify(s.tree);C.execute(s,'end_the_round',{},'end');a.equal(JSON.stringify(s.tree),before);C.beginRound(s,'继续');const found=C.execute(s,'search',{pattern:'铜钥匙',path:'过往回合历史记忆'},'find');a.equal(found.ok,true);a.match(JSON.stringify(found.result),/铜钥匙/);C.rollback(s);C.rollback(s);a.equal(V.resolve(s.tree,['workspace','过往回合历史记忆']),null);});
test('player and dice events carry world time, updated world files beat a stale cache',()=>{const s=save();s.cache={Game_World_Time:'昨夜'};C.beginRound(s,'等待');a.equal(s.events[0].worldTime,'昨夜');const result=C.execute(s,'roll_dice',{roller:'林青',description:'观察',related_attr:'观察',is_secret:false,calculate_only:true,dice_dict:{检定:'1'},target_value:null,compare_mode:null,critical_success_range:null,critical_failure_range:null,dice_combine_mode:'sum',left_modifiers:{},right_modifiers:{}},'dice');a.equal(result.ok,true);a.equal(s.events.find(x=>x.type==='dice').worldTime,'昨夜');V.writeFile(s.tree,'/workspace/世界状态和世界规则/世界共识.json','{"世界时间":"上午"}');finish(s);a.equal(s.events.find(x=>x.type==='story').worldTime,'上午');a.equal(s.events.find(x=>x.type==='round_end').worldTime,'午后');});
test('dead characters cannot act and unconscious characters can only explicitly skip',()=>{a.throws(()=>C.beginRound(save({状态:{Alive:false}}),'攻击'),/死亡/);const s=save({状态:{Enabled:false}});a.throws(()=>C.beginRound(s,'攻击'),/意识/);C.beginRound(s,'',false,'',{skip:true});a.equal(s.events[0].skip,true);a.match(s.events[0].content,/失去意识/);a.equal(s.activeRound.action,'失去意识，无法主动行动，等待局势发展。');});
test('export includes filtered character and inventory and structural changes stay readable',()=>{const s=save({姓名:'林青',技能:[{名称:'观察'}],'.秘密':'SECRET'});s.events=[{type:'story',content:'旅途',round:1}];const html=P.historyHTML(s,undefined,C.player(s));a.match(html,/人物档案/);a.match(html,/随身物品/);a.match(html,/林青/);a.doesNotMatch(html,/SECRET/);const diff=P.fields({状态:'正常'},{状态:{HP:10}});a.match(diff,/HP/);a.doesNotMatch(diff,/\[object Object\]/);a.match(P.fields({技能:[{名称:'观察'}]}),/技能.*\[1\]/);});
function legacyFile(extra=[]){const entries=[{name:'Player-p/基础信息.json',text:'{"姓名":"林青"}'},{name:'Player-p/背包.json',text:'[]'},...extra];const blob=ZIP.makeZip(entries);return {name:'参考存档.zip',arrayBuffer:()=>blob.arrayBuffer()};}
test('reference ZIP restores history, summaries, cache and continuation without exposing other private stories',async()=>{const s=await IO.importSave(legacyFile([{name:'OutputHistory.json',text:JSON.stringify([{role:'<|GM|>',type:'main',content:'旧剧情',round_count:7,world_time:'夜晚',timestamp:1700000000},{role:'<|GM|>',type:'main',content:'SECRET',is_private:true,target_player:'other',round_count:7}])},{name:'SummaryHistory.json',text:'[{"round_count":7,"content":"旧摘要","world_time":"夜晚","timestamp":1700000000}]'},{name:'ROUND_CACHE.xml',text:'{"Story_Phase":"游戏循环","Game_World_Time":"夜晚"}'},{name:'.round_count',text:'7'}]));a.equal(s.round,7);a.equal(s.status,'waiting');a.equal(s.events[0].at,1700000000000);a.equal(s.cache.Game_World_Time,'夜晚');a.equal(s.summaries[0].round,7);a.doesNotMatch(JSON.stringify(C.visibleEvents(s,'play')),/SECRET/);a.match(JSON.stringify(C.context(s,'',100000)),/旧剧情/);C.beginRound(s,'继续');a.equal(s.activeRound.number,8);});
test('broken reference history is not silently imported as a new game',async()=>{await a.rejects(IO.importSave(legacyFile([{name:'OutputHistory.json',text:'{'}])),/OutputHistory/);});
test('reference round folders restore progress when the global history file is absent',async()=>{const prefix='过往回合历史记忆/Round_4_Time_雨夜/';const s=await IO.importSave(legacyFile([{name:prefix+'回合情节.json',text:'[{"role":"<|GM|>","type":"main","content":"雨夜抵达","round_count":4,"world_time":"雨夜"}]'},{name:prefix+'回合总结.txt',text:'抵达旅馆'},{name:prefix+'ROUND_CACHE.xml',text:'{"Story_Phase":"游戏循环","Game_World_Time":"雨夜"}'}]));a.equal(s.round,4);a.equal(s.cache.Game_World_Time,'雨夜');a.equal(s.summaries[0].content,'抵达旅馆');a.equal(s.events[0].content,'雨夜抵达');});
test('archive backfill keeps existing files and does not invent missing old caches',()=>{const H=require('../src/game-history'),s=save();s.round=3;s.events=[{type:'story',round:1,worldTime:'清晨',content:'旧事'}];s.summaries=[{round:1,content:'摘要'}];H.backfill(s);const root=V.resolve(s.tree,['workspace','过往回合历史记忆','Round_1_Time_清晨']);a.ok(root);a.equal(root.children['ROUND_CACHE.xml'],undefined);root.children['回合总结.txt'].content='保留';H.backfill(s,true);a.equal(root.children['回合总结.txt'].content,'保留');});
test('dice display translates actor identifiers without replacing numeric dice results',()=>{const s=save();a.equal(P.eventContent(s,{type:'dice',roller:'p',content:'p · 检定 1d20 [12]'}),'林青 · 检定 1d20 [12]');a.match(P.exportName(s,1700000000000),/故事-2023-11-14T/);});
test('context compacts old read results without modifying durable messages or splitting tool pairs',()=>{const s=save();s.round=1;s.messages=[{role:'user',content:'行动',round:1},{role:'assistant',content:'',round:1,tool_calls:[{id:'read',type:'function',function:{name:'read_file',arguments:'{"path":"长篇.md"}'}}]},{role:'tool',round:1,tool_call_id:'read',content:JSON.stringify({ok:true,result:{content:'冗长资料'.repeat(5000)}})}];C.beginRound(s,'继续');const before=JSON.stringify(s.messages),messages=C.context(s,'系统',1000);a.ok(messages.some(m=>m.tool_calls?.[0].id==='read'));a.match(messages.find(m=>m.tool_call_id==='read').content,/长篇.md/);a.equal(JSON.stringify(s.messages),before);});
